import { v4 as uuidv4 } from "uuid";
import food from "../assets/food.jpg";
import { createSlice } from "@reduxjs/toolkit";
const initialState = {
  items: [
    {
      id: uuidv4(),
      code: "USD",
      name: "U.S. Dollars",
      symbol: "$",
      price: 200,
      img: food,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam deserunt soluta expedita consectetur, ipsa voluptas. Animi quam dolorem eos vero distinctio ex blanditiis esse eligendi hic commodi quidem, nam quod?",
    },
    {
      id: uuidv4(),
      code: "GBP",
      name: "British Pounds",
      symbol: "£",
      price: 200,
      img: food,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam deserunt soluta expedita consectetur, ipsa voluptas. Animi quam dolorem eos vero distinctio ex blanditiis esse eligendi hic commodi quidem, nam quod?",
    },
    {
      id: uuidv4(),
      code: "EUR",
      name: "Euros",
      symbol: "€",
      price: 200,
      img: food,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam deserunt soluta expedita consectetur, ipsa voluptas. Animi quam dolorem eos vero distinctio ex blanditiis esse eligendi hic commodi quidem, nam quod?",
    },
    {
      id: uuidv4(),
      code: "CAD",
      name: "Canadian Dollars",
      symbol: "CA$",
      price: 200,
      img: food,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam deserunt soluta expedita consectetur, ipsa voluptas. Animi quam dolorem eos vero distinctio ex blanditiis esse eligendi hic commodi quidem, nam quod?",
    },
    {
      id: uuidv4(),
      code: "CHF",
      name: "Swiss Francs",
      symbol: "CHF",
      price: 200,
      img: food,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam deserunt soluta expedita consectetur, ipsa voluptas. Animi quam dolorem eos vero distinctio ex blanditiis esse eligendi hic commodi quidem, nam quod?",
    },
    {
      id: uuidv4(),
      code: "AUD",
      name: "Australian Dollars",
      symbol: "A$",
      price: 200,
      img: food,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam deserunt soluta expedita consectetur, ipsa voluptas. Animi quam dolorem eos vero distinctio ex blanditiis esse eligendi hic commodi quidem, nam quod?",
    },
    {
      id: uuidv4(),
      code: "JPY",
      name: "Japanese Yen",
      symbol: "¥",
      price: 200,
      img: food,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam deserunt soluta expedita consectetur, ipsa voluptas. Animi quam dolorem eos vero distinctio ex blanditiis esse eligendi hic commodi quidem, nam quod?",
    },
    {
      id: uuidv4(),
      code: "CNY",
      name: "Chinese Yuan",
      symbol: "CN¥",
      price: 200,
      img: food,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam deserunt soluta expedita consectetur, ipsa voluptas. Animi quam dolorem eos vero distinctio ex blanditiis esse eligendi hic commodi quidem, nam quod?",
    },
    {
      id: uuidv4(),
      code: "INR",
      name: "Indian Rupees",
      symbol: "₹",
      price: 200,
      img: food,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam deserunt soluta expedita consectetur, ipsa voluptas. Animi quam dolorem eos vero distinctio ex blanditiis esse eligendi hic commodi quidem, nam quod?",
    },
    {
      id: uuidv4(),
      code: "SEK",
      name: "Swedish Krona",
      symbol: "SEK",
      price: 200,
      img: food,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam deserunt soluta expedita consectetur, ipsa voluptas. Animi quam dolorem eos vero distinctio ex blanditiis esse eligendi hic commodi quidem, nam quod?",
    },
    {
      id: uuidv4(),
      code: "BRL",
      name: "Brazilian Real",
      symbol: "R$",
      price: 200,
      img: food,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam deserunt soluta expedita consectetur, ipsa voluptas. Animi quam dolorem eos vero distinctio ex blanditiis esse eligendi hic commodi quidem, nam quod?",
    },
    {
      id: uuidv4(),
      code: "TRY",
      name: "Turkish Lira",
      symbol: "TRY",
      price: 200,
      img: food,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam deserunt soluta expedita consectetur, ipsa voluptas. Animi quam dolorem eos vero distinctio ex blanditiis esse eligendi hic commodi quidem, nam quod?",
    },
    {
      id: uuidv4(),
      code: "DKK",
      name: "Danish Krone",
      symbol: "DKK",
      price: 200,
      img: food,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam deserunt soluta expedita consectetur, ipsa voluptas. Animi quam dolorem eos vero distinctio ex blanditiis esse eligendi hic commodi quidem, nam quod?",
    },
    {
      id: uuidv4(),
      code: "MXN",
      name: "Mexican Peso",
      symbol: "MX$",
      price: 200,
      img: food,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam deserunt soluta expedita consectetur, ipsa voluptas. Animi quam dolorem eos vero distinctio ex blanditiis esse eligendi hic commodi quidem, nam quod?",
    },
    {
      id: uuidv4(),
      code: "TWD",
      name: "New Taiwan Dollars",
      symbol: "NT$",
      price: 200,
      img: food,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam deserunt soluta expedita consectetur, ipsa voluptas. Animi quam dolorem eos vero distinctio ex blanditiis esse eligendi hic commodi quidem, nam quod?",
    },
    {
      id: uuidv4(),
      code: "HKD",
      name: "Hong Kong Dollars",
      symbol: "HK$",
      price: 200,
      img: food,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam deserunt soluta expedita consectetur, ipsa voluptas. Animi quam dolorem eos vero distinctio ex blanditiis esse eligendi hic commodi quidem, nam quod?",
    },
    {
      id: uuidv4(),
      code: "NOK",
      name: "Norwegian Krone",
      symbol: "NOK",
      price: 200,
      img: food,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam deserunt soluta expedita consectetur, ipsa voluptas. Animi quam dolorem eos vero distinctio ex blanditiis esse eligendi hic commodi quidem, nam quod?",
    },
    {
      id: uuidv4(),
      code: "PLN",
      name: "Polish Zloty",
      symbol: "PLN",
      price: 200,
      img: food,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam deserunt soluta expedita consectetur, ipsa voluptas. Animi quam dolorem eos vero distinctio ex blanditiis esse eligendi hic commodi quidem, nam quod?",
    },
    {
      id: uuidv4(),
      code: "AED",
      name: "UAE Dirham",
      symbol: "AED",
      price: 200,
      img: food,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam deserunt soluta expedita consectetur, ipsa voluptas. Animi quam dolorem eos vero distinctio ex blanditiis esse eligendi hic commodi quidem, nam quod?",
    },
    {
      id: uuidv4(),
      code: "AFN",
      name: "Afghan Afghanis",
      symbol: "AFN",
      price: 200,
      img: food,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam deserunt soluta expedita consectetur, ipsa voluptas. Animi quam dolorem eos vero distinctio ex blanditiis esse eligendi hic commodi quidem, nam quod?",
    },
  ],
};

const menuSlice = createSlice({
  name: "menu",
  initialState,
  reducers: {},
});

// export const {} = menuSlice.actions;

export default menuSlice.reducer;
